title = "The future of (open) human neuroscience"
tag = "FutureOpenNeuro_Cogbases_10_11_2023"
base_url = "http://poldrack.github.io"
remote = "git@github.com:poldrack/talks-FutureOpenNeuroscience.git"
talk_url = "http://poldrack.github.io/talks-FutureOpenNeuroscience/talk/talk.html"
repo_url = "http://poldrack.github.io/talks-FutureOpenNeuroscience"
