project:
  type: website
  output-dir: ../docs

website:
  title: "The future of (open) human neuroscience"
  navbar:
    left:
      - href: http://poldrack.github.io/talks-FutureOpenNeuroscience
        text: Github page

format:
  html:
    theme: flatly
    css: styles.css

